version: '3.9'
services:
  server:
    container_name: k-grpc-server
    build: 
      context: .
      dockerfile: docker/server/Dockerfile
      target: dev
    tty: true
    ports:
      - "50058:50051"
    volumes:
      - type: bind
        source: .
        target: /go/src/app
  db:
    container_name: k-grpc-db
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    volumes:
      - type: volume
        source: k-grpc-db-volume
        target: /var/lib/mysql
      - type: bind
        source: ./docker/db/init.sql
        target: /docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: hoge
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: bakery
    ports:
      - "23306:3306"

volumes:
  k-grpc-db-volume:
