version: '3.9'
services:
  server:
    build: 
      context: .
      dockerfile: docker/server/Dockerfile
    tty: true
    ports:
      - "50058:50051"
    volumes:
      - type: bind
        source: .
        target: /go/src/app
    command: go run server/server.go
